name: pip_install_on_py3_12
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pip_install_on_py3_12:
    strategy:
      fail-fast: false
      matrix:
        module: ["PyWavelets", "git+https://github.com/PyWavelets/pywt.git", "scikit-fuzzy", "scikit-image"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: 3.12
    - run: pip install ${{ matrix.module }}
